### ISSUE TITLE
Definitions using `allOf` which don't specify a type cause a `ValueError`.

### ISSUE THREAD

**Issue by abingham** [Parquery/swagger-to#117]
If I create a definition using `allOf` that doesn't specify it's type, swagger-to raises a `ValueError` when swagger-to can't determine its type. For example:
```
basePath: /
consumes:
- application/json
info:
  description: An API
  title: An API
  version: '1.0'
definitions:
  Base:
    properties:
      base_prop:
        type: integer
  Sub:
    allOf:
      - $ref: "#/definitions/Base"
      - type: object
        properties:
          sub_prop:
            type: integer
paths:
  /:
    get:
      operationId: get.foo.bar
      responses:
        '200':
          description: Success
produces:
- application/json
swagger: '2.0'
tags:
  - description: Test API
    name: API 
```
Since `Sub` doesn't specify a `type`, I get this:
```
% python `which swagger_to_elm_client.py` --swagger_path broken.yaml --outdir gen
Traceback (most recent call last):
  File "/Users/abingham/.virtualenvs/acquisition-system/bin/swagger_to_elm_client.py", line 11, in <module>
    load_entry_point('swagger-to', 'console_scripts', 'swagger_to_elm_client.py')()
  File "/Users/abingham/repos/swagger-to/swagger_to/bin/swagger_to_elm_client.py", line 48, in main
    intermediate_typedefs = swagger_to.intermediate.to_typedefs(swagger=swagger)
  File "/Users/abingham/repos/swagger-to/swagger_to/intermediate.py", line 320, in to_typedefs
    _preallocate_named_typedefs(definition=defi, typedefs=typedefs)
  File "/Users/abingham/repos/swagger-to/swagger_to/intermediate.py", line 171, in _preallocate_named_typedefs
    raise ValueError(("Could not determine the intermediate type "
ValueError: Could not determine the intermediate type for a Swagger type definition 'Sub' (here given as JSON):
{
  "allOf": [
    {
      "$ref": "#/definitions/Base"
    },
    {
      "type": "object",
      "properties": {
        "sub_prop": {
          "type": "integer"
        }
      }
    }
  ]
}
```

**Comment by mristin** [comment]
@abingham could you please check whether the PR #119 fixes the issue for your schema?

**Comment by abingham** [comment]
This seems to work. Thanks!
