### ISSUE TITLE
Object types defined "anonymously" in `allOf` aren't defauled to type "object"

### ISSUE THREAD

**Issue by abingham** [Parquery/swagger-to#118]
Consider this spec:
```
basePath: /
consumes:
- application/json
info:
  description: An API
  title: An API
  version: '1.0'
definitions:
  Base:
    properties:
      base_prop:
        type: integer
  Sub:
    allOf:
      - $ref: "#/definitions/Base"
      - properties:
          sub_prop:
            type: integer
    type: object
paths:
  /:
    get:
      operationId: get.foo.bar
      responses:
        '200':
          description: Success
produces:
- application/json
swagger: '2.0'
tags:
  - description: Test API
    name: API 
```
The `Sub` definition doesn't specify a "type" for the "sub_prop" property, and this causes swagger-to to raise a `ValueError`:
```
% python `which swagger_to_elm_client.py` --swagger_path broken.yaml --outdir gen
Traceback (most recent call last):
  File "/Users/abingham/.virtualenvs/acquisition-system/bin/swagger_to_elm_client.py", line 11, in <module>
    load_entry_point('swagger-to', 'console_scripts', 'swagger_to_elm_client.py')()
  File "/Users/abingham/repos/swagger-to/swagger_to/bin/swagger_to_elm_client.py", line 48, in main
    intermediate_typedefs = swagger_to.intermediate.to_typedefs(swagger=swagger)
  File "/Users/abingham/repos/swagger-to/swagger_to/intermediate.py", line 324, in to_typedefs
    _resolve_substructures(definition=defi, typedefs=typedefs)
  File "/Users/abingham/.virtualenvs/acquisition-system/lib/python3.8/site-packages/icontract/_checkers.py", line 396, in wrapper
    result = func(*args, **kwargs)
  File "/Users/abingham/repos/swagger-to/swagger_to/intermediate.py", line 219, in _resolve_substructures
    raise ValueError(
ValueError: Unexpected super definition in allOf which is not of type object on line 15: RawDict([('properties', RawDict([('sub_prop', RawDict([('type', 'integer')]))]))])
```

Changing the `Sub` definition to the following fixes the problem:
```
Sub:
    allOf:
      - $ref: "#/definitions/Base"
      - type: object
        properties:
          sub_prop:
            type: integer
    type: object
```

**Comment by mristin** [comment]
@abingham could you please check if PR #119 indeed fixes this issue for you?

**Comment by abingham** [comment]
Seems to work. Thanks!
