### ISSUE TITLE
swagger_to_py_client.py doesn't generate any attributes specified in allOf

### ISSUE THREAD

**Issue by unicman** [Parquery/swagger-to#143]
Swagger contains following:

```
  Region:
    description: |
      everything you could want to know
    type: object
    allOf:
      - $ref: "#/definitions/RegionSummary"

  RegionSummary:
    type: object
    description: |
      summary information
    allOf:
      - type: object
        required:
          - id
          - realmName
          - timeCreated
        properties:
          id:
            description: Unique 
            type: string
          realmName:
            description: the name
            type: string
            minLength: 1
            maxLength: 255 # ?
          timeCreated:
            description: When the region
            type: string
            format: date-time
```

Expected output is Region class should either inherit from RegionSummary or contain all the attributes of RegionSummary. However, swagger_to_py_client.py generates empty class:

```
class Region:
    """
    Everything you could want
    """

    def to_jsonable(self) -> MutableMapping[str, Any]:
        """
        Dispatches the conversion to region_to_jsonable.

        :return: a JSON-able representation
        """
        return region_to_jsonable(self)


def new_region() -> Region:
    """Generates an instance of Region with default values."""
    return Region()
```

Does swagger-to support allOf? If yes, how to make it generate correct stub?

**Comment by mristin** [comment]
Hi @unicman ,
Swagger-to does not support inheritance yet. A pull request would be very welcome!

**Comment by mristin** [comment]
I'm closing the issue due to inactivity.

**Comment by KudryashovIlya** [comment]
Problem is still here, should I create a new issue or we can continue here?)
swagger configuration
```
  /sites/{siteId}/payment-providers/{paymentProviderId}:
    parameters:
      - $ref: "#/parameters/RequestID"
    get:
      operationId: GetSitesSiteIDPaymentProvidersPaymentProviderID
      description: Get site currenciy
      parameters:
        - description: Site ID
          in: path
          name: siteId
          required: true
          type: string
        - description: Payment ProviderId ID
          in: path
          name: paymentProviderId
          required: true
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: "#/definitions/SitePaymentProvider"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/Error"
```

generated python client:

```
class SitePaymentProviderWithCountries:
    def __init__(
            self,
            countries: List[str]) -> None:
        """Initializes with the given values."""
        self.countries = countries

    def to_jsonable(self) -> MutableMapping[str, Any]:
        """
        Dispatches the conversion to site_payment_provider_with_countries_to_jsonable.

        :return: JSON-able representation
        """
        return site_payment_provider_with_countries_to_jsonable(self)


def new_site_payment_provider_with_countries() -> SitePaymentProviderWithCountries:
    """Generates an instance of SitePaymentProviderWithCountries with default values."""
    return SitePaymentProviderWithCountries(
        countries=[])


def site_payment_provider_with_countries_from_obj(obj: Any, path: str = "") -> SitePaymentProviderWithCountries:
    """
    Generates an instance of SitePaymentProviderWithCountries from a dictionary object.

    :param obj: a JSON-ed dictionary object representing an instance of SitePaymentProviderWithCountries
    :param path: path to the object used for debugging
    :return: parsed instance of SitePaymentProviderWithCountries
    """
    if not isinstance(obj, dict):
        raise ValueError('Expected a dict at path {}, but got: {}'.format(path, type(obj)))

    for key in obj:
        if not isinstance(key, str):
            raise ValueError(
                'Expected a key of type str at path {}, but got: {}'.format(path, type(key)))

    countries_from_obj = from_obj(
        obj['countries'],
        expected=[list, str],
        path=path + '.countries')  # type: List[str]

    return SitePaymentProviderWithCountries(
        countries=countries_from_obj)


def site_payment_provider_with_countries_to_jsonable(
        site_payment_provider_with_countries: SitePaymentProviderWithCountries,
        path: str = "") -> MutableMapping[str, Any]:
    """
    Generates a JSON-able mapping from an instance of SitePaymentProviderWithCountries.

    :param site_payment_provider_with_countries: instance of SitePaymentProviderWithCountries to be JSON-ized
    :param path: path to the site_payment_provider_with_countries used for debugging
    :return: a JSON-able representation
    """
    res = dict()  # type: Dict[str, Any]

    res['countries'] = to_jsonable(
        site_payment_provider_with_countries.countries,
        expected=[list, str],
        path='{}.countries'.format(path))

    return res
```

as you may see, there is lost reference to SitePaymentProvider.

**Comment by mristin** [comment]
@KudryashovIlya would you mind creating a pull request?

I'll re-open the issue since there is definitely interest.

**Comment by KudryashovIlya** [comment]
still trying to figured out what is wrong, just hope that someone could help)
ok, if I will find solution - ill create pr

**Comment by KudryashovIlya** [comment]
got stuck with this error
```
Traceback (most recent call last):
  File "/Users/kudryashov/Work/swagger-to/venv/lib/python3.8/site-packages/icontract/_checkers.py", line 832, in wrapper
    result = func(*args, **kwargs)
  File "/Users/kudryashov/Work/swagger-to/swagger_to/py_client.py", line 1800, in generate_client_py
    class_definition={classdef: _generate_class_definition(classdef=classdef)
  File "/Users/kudryashov/Work/swagger-to/swagger_to/py_client.py", line 1800, in <dictcomp>
    class_definition={classdef: _generate_class_definition(classdef=classdef)
  File "/Users/kudryashov/Work/swagger-to/venv/lib/python3.8/site-packages/icontract/_checkers.py", line 832, in wrapper
    result = func(*args, **kwargs)
  File "/Users/kudryashov/Work/swagger-to/swagger_to/py_client.py", line 890, in _generate_class_definition
    return _CLASS_DEF_WITH_ATTRIBUTES_TPL.render(classdef=classdef, attribute_type=attribute_type)
  File "/Users/kudryashov/Work/swagger-to/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/kudryashov/Work/swagger-to/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 11, in top-level template code
  File "/Users/kudryashov/Work/swagger-to/venv/lib/python3.8/site-packages/icontract/_checkers.py", line 832, in wrapper
    result = func(*args, **kwargs)
  File "/Users/kudryashov/Work/swagger-to/swagger_to/py_client.py", line 692, in _arg_name
    return swagger_to.snake_case(_NON_IDENTIFIER_RE.sub("_", name))
TypeError: expected string or bytes-like object
```
 dont understand why name in here is Undefined
 p.s.
 error with missed allOf I fixed

**Comment by mristin** [comment]
This is a runtime typing problem. Are you sure your Swagger Spec is valid -- did you validate it with another tool?

**Comment by KudryashovIlya** [comment]
yeap, checked on several tool, all checks passed

problem is that an object of the Attribute class is expected that has an attribute name

in my implementation, everything that was in allOf I store it as a dictionary, which, as you understand, does not have such an attribute

currently, `properties = collections.OrderedDict()` and I think that if I change DictDef and add attributes as in Attribute - this is one of the solutions

**Comment by mristin** [comment]
@KudryashovIlya could you please elaborate a bit? I am pretty lost what the input and the exact errors are?

Can you please copy/paste the relevant snippets here as well, and point me about what is unclear/surprising?

(Please apologize that I can not dig more into the issue myself. I am currently overwhelmed with the family stuff.)
