### ISSUE TITLE
ValueError: Unexpected definition: OrderedDict([('description', 'response payload'), ('allOf', [<swagger_to.swagger.RawDict object at 0x7fdf21b57358>])])

### ISSUE THREAD

**Issue by bdrung** [Parquery/swagger-to#72]
Running `swagger_to_py_client.py` on a swagger.json file for an internal API fails:

```python
Traceback (most recent call last):
  File "swagger_to_py_client.py", line 57, in <module>
    main()
  File "swagger_to_py_client.py", line 36, in main
    intermediate_typedefs = swagger_to.intermediate.to_typedefs(swagger=swagger)
  File "swagger_to/intermediate.py", line 290, in to_typedefs
    _resolve_substructures(definition=defi, typedefs=typedefs)
  File "swagger_to/intermediate.py", line 203, in _resolve_substructures
    propdef.typedef = _anonymous_or_get_typedef(original_typedef=prop_typedef, typedefs=typedefs)
  File "swagger_to/intermediate.py", line 267, in _anonymous_or_get_typedef
    raise ValueError("Unexpected definition: {!r}".format(original_typedef.raw_dict.adict))
ValueError: Unexpected definition: OrderedDict([('description', 'response payload'), ('allOf', [<swagger_to.swagger.RawDict object at 0x7fdf21b57358>])])
```

I am offer my help to debug this issue, but I cannot share the swagger.json file.

**Comment by mristin** [comment]
Hi @bdrung,
Thanks for reporting!

Could you please at least give us a minimal schema that makes swagger-to crash?

**Comment by mristin** [comment]
@radomsak I think this issue can be closed due to inactivity?
